// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(NinjaManagerContext))]
    [Migration("20201022235041_AddSkinURL")]
    partial class AddSkinURL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 200,
                            Category = 0,
                            Cost = 300,
                            Description = "A cheap basic hat which makes you go a little faster.",
                            ImageUrl = "/images/equipment/head/golden_helmet.png",
                            Intelligence = 30,
                            Name = "Fancy Hat",
                            Strength = 5
                        },
                        new
                        {
                            Id = 2,
                            Agility = -50,
                            Category = 0,
                            Cost = 20,
                            Description = "A creepy pumpkin to scare others.",
                            ImageUrl = "/images/equipment/head/carved_pumpkin.png",
                            Intelligence = -40,
                            Name = "Pumpkin",
                            Strength = 25
                        },
                        new
                        {
                            Id = 3,
                            Agility = -50,
                            Category = 1,
                            Cost = 800,
                            Description = "Covers the upper body of the player.",
                            ImageUrl = "/images/equipment/chest/diamond_chestplate.png",
                            Intelligence = 20,
                            Name = "Diamond Chestplate",
                            Strength = 100
                        });
                });

            modelBuilder.Entity("Data.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("SkinUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gold = 1500,
                            Name = "Cool ninja"
                        },
                        new
                        {
                            Id = 2,
                            Gold = 2000,
                            Name = "Awesome_ninja67"
                        });
                });

            modelBuilder.Entity("Data.NinjaEquipment", b =>
                {
                    b.Property<int>("NinjaId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("NinjaId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("NinjaEquipment");

                    b.HasData(
                        new
                        {
                            NinjaId = 1,
                            EquipmentId = 1
                        });
                });

            modelBuilder.Entity("Data.NinjaEquipment", b =>
                {
                    b.HasOne("Data.Equipment", "Equipment")
                        .WithMany("NinjaEquipment")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Ninja", "Ninja")
                        .WithMany("NinjaEquipment")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
