// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(NinjaManagerContext))]
    [Migration("20201025225511_AddSeedDataAllRemainingItems")]
    partial class AddSeedDataAllRemainingItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 200,
                            Category = 0,
                            Cost = 300,
                            Description = "A cheap basic hat which makes you go a little faster.",
                            ImageUrl = "/images/equipment/helmet/golden_helmet.png",
                            Intelligence = 30,
                            Name = "Fancy Hat",
                            Strength = 5
                        },
                        new
                        {
                            Id = 2,
                            Agility = -200,
                            Category = 0,
                            Cost = 600,
                            Description = "If you scared just hide in your shell.",
                            ImageUrl = "/images/equipment/helmet/turtle_shell.png",
                            Intelligence = 20,
                            Name = "Shelly",
                            Strength = 140
                        },
                        new
                        {
                            Id = 3,
                            Agility = -50,
                            Category = 0,
                            Cost = 240,
                            Description = "A creepy pumpkin to scare others.",
                            ImageUrl = "/images/equipment/helmet/carved_pumpkin.png",
                            Intelligence = 130,
                            Name = "Pumpkin",
                            Strength = -10
                        },
                        new
                        {
                            Id = 4,
                            Agility = -40,
                            Category = 1,
                            Cost = 800,
                            Description = "Covers the upper body of the player.",
                            ImageUrl = "/images/equipment/chest/diamond_chestplate.png",
                            Intelligence = 20,
                            Name = "Diamond Chestplate",
                            Strength = 100
                        },
                        new
                        {
                            Id = 5,
                            Agility = -50,
                            Category = 1,
                            Cost = 1200,
                            Description = "Even lava can't beat this",
                            ImageUrl = "/images/equipment/chest/netherite_chestplate.png",
                            Intelligence = 40,
                            Name = "Netherite Chestplate",
                            Strength = 300
                        },
                        new
                        {
                            Id = 6,
                            Agility = 150,
                            Category = 1,
                            Cost = 350,
                            Description = "Helps a bit.",
                            ImageUrl = "/images/equipment/chest/leather_tunic.png",
                            Intelligence = -70,
                            Name = "Leather Chestplate",
                            Strength = 10
                        },
                        new
                        {
                            Id = 10,
                            Agility = 110,
                            Category = 3,
                            Cost = 90,
                            Description = "Nice thick leather to keep your feet warm.",
                            ImageUrl = "/images/equipment/boots/leather_boots.png",
                            Intelligence = -30,
                            Name = "Leather Boots",
                            Strength = 0
                        },
                        new
                        {
                            Id = 11,
                            Agility = -30,
                            Category = 3,
                            Cost = 220,
                            Description = "Just some nice shiny shoes.",
                            ImageUrl = "/images/equipment/boots/iron_boots.png",
                            Intelligence = 10,
                            Name = "Iron Boots",
                            Strength = 160
                        },
                        new
                        {
                            Id = 12,
                            Agility = 20,
                            Category = 3,
                            Cost = 440,
                            Description = "Heavy metal rock shoes.",
                            ImageUrl = "/images/equipment/boots/netherite_boots.png",
                            Intelligence = -30,
                            Name = "Netherite Boots",
                            Strength = 160
                        },
                        new
                        {
                            Id = 13,
                            Agility = 10,
                            Category = 4,
                            Cost = 40,
                            Description = "Cheap gold but it's good looking.",
                            ImageUrl = "/images/equipment/sword/golden_sword.png",
                            Intelligence = 10,
                            Name = "Golden Sword",
                            Strength = 20
                        },
                        new
                        {
                            Id = 14,
                            Agility = -30,
                            Category = 4,
                            Cost = 220,
                            Description = "Will do the trick.",
                            ImageUrl = "/images/equipment/sword/iron_sword.png",
                            Intelligence = 10,
                            Name = "Iron Sword",
                            Strength = 160
                        },
                        new
                        {
                            Id = 15,
                            Agility = 80,
                            Category = 4,
                            Cost = 640,
                            Description = "Heavy metal blade of doom.",
                            ImageUrl = "/images/equipment/sword/netherite_sword.png",
                            Intelligence = 60,
                            Name = "Netherite Sword",
                            Strength = 430
                        },
                        new
                        {
                            Id = 16,
                            Agility = 0,
                            Category = 5,
                            Cost = 300,
                            Description = "To see everything.",
                            ImageUrl = "/images/equipment/potion/Potion_of_Night_Vision.gif",
                            Intelligence = 300,
                            Name = "Night Vision Potion",
                            Strength = 0
                        },
                        new
                        {
                            Id = 17,
                            Agility = 0,
                            Category = 5,
                            Cost = 300,
                            Description = "If you need some more time.",
                            ImageUrl = "/images/equipment/potion/Potion_of_Regeneration.gif",
                            Intelligence = 0,
                            Name = "Regeneration potion",
                            Strength = 300
                        },
                        new
                        {
                            Id = 18,
                            Agility = 300,
                            Category = 5,
                            Cost = 300,
                            Description = "If you're in a hurry.",
                            ImageUrl = "/images/equipment/potion/Potion_of_Swiftness.gif",
                            Intelligence = 0,
                            Name = "Swiftness potion",
                            Strength = 0
                        });
                });

            modelBuilder.Entity("Data.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("SkinUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gold = 1500,
                            Name = "Cool ninja"
                        },
                        new
                        {
                            Id = 2,
                            Gold = 2000,
                            Name = "Awesome_ninja67"
                        },
                        new
                        {
                            Id = 3,
                            Gold = 1200,
                            Name = "Blockplacer"
                        },
                        new
                        {
                            Id = 4,
                            Gold = 3200,
                            Name = "Stealthy"
                        },
                        new
                        {
                            Id = 5,
                            Gold = 4000,
                            Name = "Epicness"
                        },
                        new
                        {
                            Id = 6,
                            Gold = 2500,
                            Name = "Epic_Fat"
                        });
                });

            modelBuilder.Entity("Data.NinjaEquipment", b =>
                {
                    b.Property<int>("NinjaId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("NinjaId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("NinjaEquipments");

                    b.HasData(
                        new
                        {
                            NinjaId = 1,
                            EquipmentId = 3
                        },
                        new
                        {
                            NinjaId = 1,
                            EquipmentId = 5
                        },
                        new
                        {
                            NinjaId = 3,
                            EquipmentId = 1
                        },
                        new
                        {
                            NinjaId = 3,
                            EquipmentId = 6
                        },
                        new
                        {
                            NinjaId = 6,
                            EquipmentId = 2
                        },
                        new
                        {
                            NinjaId = 6,
                            EquipmentId = 4
                        },
                        new
                        {
                            NinjaId = 4,
                            EquipmentId = 2
                        },
                        new
                        {
                            NinjaId = 4,
                            EquipmentId = 6
                        });
                });

            modelBuilder.Entity("Data.NinjaEquipment", b =>
                {
                    b.HasOne("Data.Equipment", "Equipment")
                        .WithMany("Ninjas")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Ninja", "Ninja")
                        .WithMany("Equipments")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
