// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(NinjaManagerContext))]
    [Migration("20201004143337_MoreDetailedSeedData")]
    partial class MoreDetailedSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Equipment", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Name = "Fancy Hat",
                            Agility = 200,
                            Category = 0,
                            Cost = 300,
                            Intelligence = 30,
                            Strength = 5
                        },
                        new
                        {
                            Name = "Pumpkin",
                            Agility = 200,
                            Category = 0,
                            Cost = 20,
                            Intelligence = -40,
                            Strength = 15
                        },
                        new
                        {
                            Name = "Diamond Chestplate",
                            Agility = -50,
                            Category = 1,
                            Cost = 800,
                            Intelligence = 20,
                            Strength = 100
                        });
                });

            modelBuilder.Entity("Data.Ninja", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Name = "Awesome_ninja67",
                            Gold = 2000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
